import {login,logout,handleAuthCallback,acceptInvite,updateUser} from '@netlify/identity';
import {inviteTokenFromLink} from '../lib/invite-link.mjs';
import {freshness} from '../lib/snapshot.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>Number.isFinite(Date.parse(t))?new Date(t).toLocaleString():'Not recorded';
let snapshot=null,view='overview',selected='',callback=null,localReview=false;
const link=(url,label)=>{try{const u=new URL(url);return u.protocol==='https:'?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'';}catch{return '';}};
const metric=(n,label)=>`<div class="metric"><strong>${esc(n)}</strong><span>${esc(label)}</span></div>`;
const matches=b=>!selected||b===selected;
function progress(episodes){let total=0,made=0,blocked=0;for(const e of episodes)for(const s of Object.values(e.stages)){total++;if(/block|auth_required/.test(s.state||''))blocked++;else if(/schedul|live/.test(s.state||'')||['built','done','complete'].includes(s.state))made++;}return {total,made,blocked};}
function leadInbox(){return snapshot?.leadInbox&&Array.isArray(snapshot.leadInbox.sources)&&Array.isArray(snapshot.leadInbox.events)?snapshot.leadInbox:{observedAt:null,sources:[],events:[]};}
function leadState(value){return ['healthy','attention','blocked','unknown','not_connected'].includes(value)?value:'unknown';}
function leadLabel(value){return ({healthy:'Healthy',attention:'Needs attention',blocked:'Blocked',unknown:'Unknown',not_connected:'Not connected'})[leadState(value)];}
function leadEvent(e){const contact=[e.contactName,e.phone,e.email].filter(Boolean).join(' · ')||'Contact details were not supplied';const business=e.businessName||e.businessId||'Business not identified';return `<article class="lead-event"><div class="lead-event-head"><span class="badge">${esc(e.eventType||'Incoming activity')}</span><span class="lead-time">${esc(date(e.occurredAt))}</span></div><h3>${esc(e.source||business)}</h3><p class="lead-contact">${esc(contact)}</p>${e.intent?`<p><b>Likely intent:</b> ${esc(e.intent)}</p>`:''}${e.message?`<p class="lead-message">${esc(e.message)}</p>`:'<p class="muted">No message text was included by this source.</p>'}<div class="lead-event-foot"><span>${esc(business)}</span><span>${esc(e.status||'New')}</span>${link(e.contactUrl,'Open contact')}</div></article>`;}
function renderLeads(){const inbox=leadInbox(),events=inbox.events.filter(e=>!selected||e.businessId===selected),sources=inbox.sources.filter(s=>!selected||!s.businessId||s.businessId===selected),attention=sources.filter(s=>leadState(s.state)!=='healthy').length,newCount=events.filter(e=>(e.status||'new').toLowerCase()==='new').length;const health=sources.length?`<div class="lead-sources">${sources.map(s=>`<article class="lead-source"><div><h3>${esc(s.name||s.id||'Unlabeled source')}</h3><p>${esc(s.kind||'Lead source')}</p></div><span class="lead-state ${leadState(s.state)}">${esc(leadLabel(s.state))}</span><small>Last evidence: ${esc(date(s.observedAt))}</small>${s.detail?`<p>${esc(s.detail)}</p>`:''}${s.nextStep?`<p class="muted"><b>Next:</b> ${esc(s.nextStep)}</p>`:''}</article>`).join('')}</div>`:'<section class="empty-leads"><h3>No lead-source health feed has been published.</h3><p>This is intentionally not shown as a healthy, empty inbox. The private ingest path is not connected yet, so the dashboard cannot say whether it has seen every lead.</p></section>';return `<h2>Lead inbox</h2><p class="notice">This is a read-only owner view. Opening an item does not mark it read, contact anyone, or change its source record.</p><div class="lead-metrics">${metric(events.length,'Recorded incoming events')}${metric(newCount,'New events')}${metric(attention,'Sources needing attention')}${metric(sources.length?freshness(inbox.observedAt):'—','Lead feed freshness')}</div><section class="lead-section"><div class="section-title"><h3>Channel health</h3><span>Each channel must prove its last successful check</span></div>${health}</section><section class="lead-section"><div class="section-title"><h3>Incoming activity</h3><span>${events.length?'Newest first':'No live events yet'}</span></div>${events.length?`<div class="lead-events">${events.slice().sort((a,b)=>(Date.parse(b.occurredAt)||0)-(Date.parse(a.occurredAt)||0)).map(leadEvent).join('')}</div>`:'<section class="empty-leads"><h3>There are no recorded events in this snapshot.</h3><p>That does not mean no one has contacted you. The source-health section must be green and current before an empty inbox can be trusted.</p></section>'}</section>`;}
function render(){if(!snapshot)return;const rows=snapshot.episodes.filter(e=>!selected||e.businessIds?.includes(selected)),p=progress(rows),name=snapshot.businesses.find(b=>b.id===selected)?.name||'All businesses';
 $('freshness').textContent=`${freshness(snapshot.observedAt)} content records · ${date(snapshot.observedAt)}. HE evidence: ${freshness(snapshot.revenueObservedAt)} · ${date(snapshot.revenueObservedAt)}. Refreshing this page does not run a new source check.`;
 let html='';
 const failed=snapshot.operations.filter(o=>matches(o.businessId)&&['failed','interrupted','missed'].includes(o.phase));
 const open=snapshot.operations.filter(o=>matches(o.businessId)&&['planned','queued','scheduled','running'].includes(o.phase));
 if(view==='overview')html=`<div class="attention"><button data-jump="leads"><strong>${leadInbox().sources.filter(s=>leadState(s.state)!=='healthy').length||'—'}</strong><span>Lead sources need review</span><small>See the Lead inbox →</small></button><button data-jump="work"><strong>${failed.length}</strong><span>Failed or uncertain checks</span><small>Historical results, review before retry →</small></button><button data-jump="work"><strong>${open.length}</strong><span>Open recorded operations</span><small>Review owners and next steps →</small></button></div><div class="section-title"><h2>Your next three moves</h2><span>Finish before expanding</span></div><p class="muted">Recommended focus, recorded ${esc(date(snapshot.focusUpdatedAt))}. Existing obligations and release gates still apply.</p><div class="cards">${snapshot.focus.filter(f=>!selected||!f.businessId||f.businessId===selected).map((f,i)=>`<article class="card"><span class="number">FOCUS ${i+1}</span><h3>${esc(f.title)}</h3><div class="next"><b>Next move</b><p>${esc(f.next)}</p><details><summary>Outcome & proof</summary><p>${esc(f.outcome)}</p><small>Proof: ${esc(f.proof)}</small></details></div><button class="focus-action" data-jump="${f.id==='outreach'?'revenue':f.id==='ship'?'work':'content'}">Review this work →</button></article>`).join('')||'<p>No featured priority is mapped to this business. Review its existing work before adding a new campaign.</p>'}</div>${flight(rows,p,name)}<div class="metrics">${metric('—','Attributed inquiries: not connected')}${metric('—','Appointments: not connected')}${metric('—','Revenue: not connected')}${metric('Pending','Claude ranking feed')}</div>`;
 if(view==='leads')html=renderLeads();
 if(view==='content')html=`<h2>${esc(name)} · Content</h2>${flight(rows,p,name)}<p class="muted">Recorded production stages are not campaign results. Check destination receipts before treating “live” as verified.</p>${rows.map(e=>`<article class="row"><small>${esc(e.date)} · ${esc(e.id)}</small><h3>${esc(e.title)}</h3><div class="stages">${Object.entries(e.stages).map(([k,s])=>`<div class="stage"><small>${esc(k.replaceAll('_',' '))}</small><p>${esc(s.state||'Unknown')}</p>${link(s.url,'Recorded destination')}</div>`).join('')}</div></article>`).join('')||'<p>No linked episode records.</p>'}`;
 if(view==='revenue')html=`<h2>Email & calling · ${esc(name)}</h2><p class="notice">These are configuration reads. Counts do not prove delivery, a cleared calling list, callbacks or appointments.</p><div class="cards">${snapshot.accounts.filter(a=>matches(a.id)).map(a=>`<article class="card"><h3>${esc(a.name)}</h3><small>${freshness(a.observedAt)} · ${esc(date(a.observedAt))}</small>${a.error?`<p class="error">${esc(a.error)}</p>`:`<div class="table-wrap"><table><tbody>${Object.entries(a.counts).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.error?'Unknown':esc(v.returned??'Unknown')}${v.limited?' (limited)':''}</td></tr>`).join('')}</tbody></table></div>`}<p>Send and dial controls stay with the existing operator.</p></article>`).join('')||'<p>No account read is mapped to this business.</p>'}</div>`;
 if(view==='work'){const ops=snapshot.operations.filter(o=>matches(o.businessId));html=`<h2>Plans & blockers</h2><p class="notice">Remote planning and recovery are not connected yet. Existing recorded work appears below. No click here will restart, schedule or send anything.</p><h3>Recorded operations</h3>${ops.map(o=>`<article class="row"><span class="badge">${esc(o.phase)}</span><small>${esc(o.taskId)} · ${esc(o.owner)}</small><p>${esc(o.nextStep)}</p><small>Scheduled: ${esc(date(o.dueAt))} · Updated: ${esc(date(o.finishedAt||o.updatedAt||o.createdAt))}</small></article>`).join('')||'<p class="muted">No recorded operations in this business view.</p>'}<h3>Shared workstreams</h3><p class="muted">These shared tasks can span businesses.</p>${snapshot.tasks.map(t=>`<article class="row"><span class="badge">${esc(t.status)}</span><small>${esc(t.id)} · ${esc(t.owner)} · ${esc(t.lastUpdate||'Update not recorded')}</small><h3>${esc(t.name)}</h3><p>${esc(t.nextStep)}</p>${t.gates?.length?`<small>Existing gates: ${esc(t.gates.join(', '))}</small>`:''}</article>`).join('')}`;}
 if(view==='agents')html=`<h2>People, agents & ranking</h2><div class="cards"><article class="card"><h3>Claude</h3><p>Ranking, search and AI visibility. Strategy and editorial ownership.</p><span class="badge">Ranking feed not connected</span><p>${esc(snapshot.connections?.ranking)}</p></article><article class="card"><h3>MacV Mac / Codex</h3><p>Content operations, integrations, verification and completion evidence.</p><span class="badge">Remote dispatch not connected</span><p>${esc(snapshot.connections?.dispatch)}</p></article><article class="card"><h3>Shared record</h3><p>Mission Control holds work, owners and next steps. A hosted snapshot is a view of that record.</p><p>No automatic paid API fallback. A dashboard refresh does not wake an agent.</p></article></div><h3>Last observed machines</h3>${snapshot.workers.map(w=>`<article class="row"><h3>${esc(w.name)}</h3><span class="badge">${freshness(w.observedAt)==='Recent'?(w.reachable?'Reachable when checked':'Unavailable when checked'):'Current state unknown'}</span><small>${esc(date(w.observedAt))}</small></article>`).join('')}`;
 $('view').innerHTML=html;
 $('view').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
 $('local-actions').hidden=!localReview||!snapshot.localControlsAvailable;
 $('access-label').textContent=localReview?'Local view · remote access in setup':'Signed-in workspace';
}
function flight(rows,p,name){const circumference=440,fill=p.total?circumference*p.made/p.total:0;return `<section class="flight"><svg class="ring" viewBox="0 0 180 180" role="img" aria-label="${p.made} of ${p.total} stages recorded made or reported live"><circle cx="90" cy="90" r="82" fill="none" stroke="#294958"/><circle cx="90" cy="90" r="70" fill="none" stroke="#273c48" stroke-width="8"/><circle cx="90" cy="90" r="70" fill="none" stroke="#8ce4e9" stroke-width="8" stroke-dasharray="${fill} ${circumference}" transform="rotate(-90 90 90)"/><text x="90" y="87" text-anchor="middle" font-size="30">${p.made}/${p.total}</text><text x="90" y="109" text-anchor="middle" font-size="10">RECORDED STAGES</text></svg><div><p class="eyebrow">${esc(name)}</p><h2>Content moving toward a destination</h2><div class="stages"><div class="stage"><strong>${rows.length}</strong>Episode records</div><div class="stage"><strong>${p.blocked}</strong>Blocked stages</div><div class="stage"><strong>—</strong>Attribution pending</div></div><p class="muted">The ring counts records marked made, done, live or scheduled. It does not measure revenue or independently verified publication.</p></div></section>`;}
async function load(){const r=await fetch('/api/control-status',{cache:'no-store',credentials:'same-origin'});const d=await r.json();if(r.status===401||r.status===403){snapshot=null;$('view').replaceChildren();$('room').hidden=true;$('login').hidden=false;$('signout').hidden=r.status===401;$('login-feedback').textContent=d.error;return;}if(r.status===503&&d.authorized&&!snapshot){$('login').hidden=true;$('room').hidden=false;$('signout').hidden=false;$('access-label').textContent='Signed in · awaiting first status feed';$('freshness').textContent=d.error;$('view').innerHTML='<h2>Your sign-in works.</h2><p>MacV Mac still needs to connect and verify the private business feed. Use Refresh status after that step.</p>';return;}if(!r.ok)throw Error(d.error||'Status unavailable');snapshot=d;localReview=r.headers.get('X-Control-Review')==='local';$('login').hidden=true;$('room').hidden=false;$('signout').hidden=false;$('access-label').textContent=r.headers.get('X-Control-Review')==='local'?'Local review · sign-in not tested':'Signed-in workspace';$('error').hidden=true;const options=d.businesses.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');$('business').innerHTML='<option value="">All businesses</option>'+options;$('business').value=selected;render();}
function failure(e){if(snapshot){render();$('error').hidden=false;$('error').textContent='Refresh failed. Showing previously loaded records: '+e.message;}else $('login-feedback').textContent=e.message;}
function switchView(next){view=next;document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.view===view));render();}
$('business').onchange=e=>{selected=e.target.value;render();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$('refresh').onclick=()=>load().catch(failure);
$('login-form').onsubmit=async e=>{e.preventDefault();$('login-submit').disabled=true;try{if(callback?.type==='invite')await acceptInvite(callback.token,$('password').value);else if(callback?.type==='recovery')await updateUser({password:$('password').value});else await login($('email').value,$('password').value);$('password').value='';callback=null;await load();}catch(e){$('login-feedback').textContent=e.message;}finally{$('login-submit').disabled=false;}};
$('signout').onclick=async()=>{snapshot=null;$('view').replaceChildren();$('room').hidden=true;$('login').hidden=false;try{await logout();$('signout').hidden=true;$('access-label').textContent='Private workspace';$('login-feedback').textContent='Signed out.';}catch{$('login-feedback').textContent='Sign-out could not be confirmed. Close this page and clear the site session.';}};
(async()=>{try{callback=await handleAuthCallback();if(['invite','recovery'].includes(callback?.type)){$('email-label').hidden=true;$('email').required=false;$('password').autocomplete='new-password';$('login-submit').textContent='Set password';$('login-feedback').textContent='Choose your password to finish private access.';return;}await load();}catch(e){failure(e);}})();
setInterval(()=>{if(snapshot)load().catch(failure);},60000);

$('use-invite').onclick=()=>{try{callback={type:'invite',token:inviteTokenFromLink($('invite-link').value,location.origin)};$('invite-link').value='';$('invite-help').hidden=true;$('email-label').hidden=true;$('email').required=false;$('password').autocomplete='new-password';$('login-submit').textContent='Set password';$('login-feedback').textContent='Choose your password to accept your private invitation.';$('password').focus();}catch(e){$('invite-feedback').textContent=e.message;}};
